// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: photos.proto

package photo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PicsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PicsReq) Reset() {
	*x = PicsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_photos_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PicsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PicsReq) ProtoMessage() {}

func (x *PicsReq) ProtoReflect() protoreflect.Message {
	mi := &file_photos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PicsReq.ProtoReflect.Descriptor instead.
func (*PicsReq) Descriptor() ([]byte, []int) {
	return file_photos_proto_rawDescGZIP(), []int{0}
}

func (x *PicsReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PicsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pid    string `protobuf:"bytes,2,opt,name=pid,proto3" json:"pid,omitempty"`
	ItemId string `protobuf:"bytes,3,opt,name=ItemId,proto3" json:"ItemId,omitempty"`
	Text   string `protobuf:"bytes,4,opt,name=Text,proto3" json:"Text,omitempty"`
	Src    string `protobuf:"bytes,5,opt,name=Src,proto3" json:"Src,omitempty"`
}

func (x *PicsRes) Reset() {
	*x = PicsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_photos_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PicsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PicsRes) ProtoMessage() {}

func (x *PicsRes) ProtoReflect() protoreflect.Message {
	mi := &file_photos_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PicsRes.ProtoReflect.Descriptor instead.
func (*PicsRes) Descriptor() ([]byte, []int) {
	return file_photos_proto_rawDescGZIP(), []int{1}
}

func (x *PicsRes) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PicsRes) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

func (x *PicsRes) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *PicsRes) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PicsRes) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

var File_photos_proto protoreflect.FileDescriptor

var file_photos_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x68, 0x6f, 0x74, 0x6f, 0x22, 0x19, 0x0a, 0x07, 0x50, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x69, 0x0a, 0x07, 0x50, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x70,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x49,
	0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x65, 0x78, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x72, 0x63,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x53, 0x72, 0x63, 0x32, 0x2e, 0x0a, 0x04, 0x70,
	0x69, 0x63, 0x73, 0x12, 0x26, 0x0a, 0x04, 0x70, 0x69, 0x63, 0x73, 0x12, 0x0e, 0x2e, 0x70, 0x68,
	0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x70, 0x68,
	0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x42, 0x09, 0x5a, 0x07, 0x2e,
	0x2f, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_photos_proto_rawDescOnce sync.Once
	file_photos_proto_rawDescData = file_photos_proto_rawDesc
)

func file_photos_proto_rawDescGZIP() []byte {
	file_photos_proto_rawDescOnce.Do(func() {
		file_photos_proto_rawDescData = protoimpl.X.CompressGZIP(file_photos_proto_rawDescData)
	})
	return file_photos_proto_rawDescData
}

var file_photos_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_photos_proto_goTypes = []interface{}{
	(*PicsReq)(nil), // 0: photo.PicsReq
	(*PicsRes)(nil), // 1: photo.PicsRes
}
var file_photos_proto_depIdxs = []int32{
	0, // 0: photo.pics.pics:input_type -> photo.PicsReq
	1, // 1: photo.pics.pics:output_type -> photo.PicsRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_photos_proto_init() }
func file_photos_proto_init() {
	if File_photos_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_photos_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PicsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_photos_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PicsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_photos_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_photos_proto_goTypes,
		DependencyIndexes: file_photos_proto_depIdxs,
		MessageInfos:      file_photos_proto_msgTypes,
	}.Build()
	File_photos_proto = out.File
	file_photos_proto_rawDesc = nil
	file_photos_proto_goTypes = nil
	file_photos_proto_depIdxs = nil
}
