// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	photo "media-zero/service/photos/api/internal/handler/photo"
	"media-zero/service/photos/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/pics/:page",
				Handler: photo.PicsHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/star/:id",
				Handler: photo.StarHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/step/:id",
				Handler: photo.StepHandler(serverCtx),
			},
		},
	)
}
