// Code generated by goctl. DO NOT EDIT!
// Source: photos.proto

package server

import (
	"context"

	"media-zero/service/photos/rpc/internal/logic"
	"media-zero/service/photos/rpc/internal/svc"
	"media-zero/service/photos/rpc/photo"
)

type PicsServer struct {
	svcCtx *svc.ServiceContext
	photo.UnimplementedPicsServer
}

func NewPicsServer(svcCtx *svc.ServiceContext) *PicsServer {
	return &PicsServer{
		svcCtx: svcCtx,
	}
}

func (s *PicsServer) Pics(ctx context.Context, in *photo.PicsReq) (*photo.PicsRes, error) {
	l := logic.NewPicsLogic(ctx, s.svcCtx)
	return l.Pics(in)
}
